### ISSUE TITLE
New version 1.2.2 fresh install is broken

### ISSUE THREAD

**Issue by rustyworks** [xeBuz/Flask-Validator#41]
This error occurs when trying to install the newest Flask-Validator (1.2.2)
And if we check the zip version from https://pypi.python.org/pypi/Flask-Validator/1.2.2, the requirements.txt doesn't included.

```
Collecting Flask-Validator
  Using cached Flask-Validator-1.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-s5jumgzv/Flask-Validator/setup.py", line 11, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

Thanks

**Comment by xeBuz** [comment]
New release `1.2.3` fixed.
Thanks for notice this
